Revises nhmmer.c for better input error handling
While debugging iss #319, incidentally found out that nhmmer does not
give useful error messages on bad inputs. For example, erroneously
giving it a CM file instead of an HMM just gives an obscure code 7:

    nhmmer --tblout foo.1 --rna --watson tRNA5.c.cm Rfam.seed.fa
    Error: Error reading query file tRNA5.c.cm (7)

This is because nhmmer tries to autodetect a HMM vs. seqfile
vs. msafile query by cascading through parser failures. So when HMM
parsing fails, it does not issue specific and useful failure warnings;
instead it moves on to trying to open it as a sequence file, and then
as an MSA file.

Decided to refactor this behavior so that we can get useful error
messages for bad query file formats. This opened several cans of
worms.

- Reorganized and streamlined. Add a struct cfg_s to organize
  input/output information. 1062 lines now, down from 1279. I tried to
  limit changes to just input/output file handling, rather than
  getting deeper into nhmmer's logic, even though I'm also concerned
  now about the implementation of things like esl_sqio_ReadBlock().

- Added --qseq, --qmsa options for explicit alternative queries, making
  profile HMM query default.

- Added --fmindex option for explicitly asking for FM-index acceleration,
  with target DB in FM-index binary format.

- Removed --qsingle_seqs option; --qseq supersedes it.

- Remove --dna, --rna options. Input must be DNA|RNA; nhmmer is for
  nucleic acid comparison only. There is no reason for nhmmer to
  autodetect alphabets or allow query or target to be protein.

- Remove --singlemx, make using DNA1 matrix the default for single seq
  queries (paralleling phmmer)

- Remove --mx option (useless, because only DNA1 is available in our code)

- Fixed a bug in p7_Pipeline_LongTarget() where p7_bg_FilterScore
  was being called even if the bias filter is off, resulting in the
  bias score being calculated on uninitialized garbage (which lights
  up the msan memory sanitizer); but p7_Pipeline_LongTarget did not
  use the result of this function call anyway.

- Put in a workaround for a problem where MSA files can't be
  read as target seqfile: `nhmmer test.hmm test.sto` hangs
  infinitely. The problem is somewhere in the convoluted
  esl_sqio_ReadBlock() logic, but I don't yet know where. For now, I
  shut off the ability to read alignment file formats sequentially as
  target seqfiles.

- renames `makehmmerdb` to `hmmer-makefmdb` (and its man page), along
  with other changes to make more clear that the use of FM-index
  acceleration is an experimental capability. I don't trust this code,
  and it is not true that the sensitivity loss is "small".

- Rewrote nhmmer man page. Several details were incorrect, apparent
  copy/paste errors from the phmmer man page.

- Toggle default vs FM-index paths using cfg->dbfp vs. cfg->fmdb non-NULL,
  trying to simplify convoluted/nested conditional compilation paths.

- Adds p7ENABLE_FMINDEX flag for conditional compilation of FM-index support.
  Code was improperly using eslENABLE_SSE flag for this.

- Set default F1=0.02 in getopts structure; handle FM-index default of
  0.03 in initialization.

- Pulled some logic out to aux functions: assign_msa_name(),
  create_fm_scoredata(), output_optional_msa().

- Renamed _loop() functions to thread_director(), thread_worker(),
  serial_processor()

- Updated i17-stdin.pl, which checks for a particular error message
  when more than one - (stdin pipe) is used on the command line, to check
  for the revised error message