There was a lingering reference to null3.o in the LIBOBJS section of Makefile.in. This caused an error in building up hmmerlib.a, which caused downstream "undefined reference to" errors to arise (at least in a fresh checkout).
The particular line that was causing trouble was (while in src/search):
% /usr/bin/ar  -r ../../src/libhmmer.a modelconfig.o null3.o p7_pipeline.o p7_pipeline_mpi.o tophits_output.o tophits_output_tabular.o > /dev/null 2>&1 

This would have raised an error
   /usr/bin/ar: null3.o: No such file or directory
but the '> /dev/null/' caused it to remain silent.

(do we want make to recognize that sort of failure, and complain about it?) 



git-svn-id: https://svn.janelia.org/eddylab/eddys/src/hmmer/trunk@4354 db3e70e4-12e1-0310-b23f-81a6e3d09ba7