Fixes issues in user error reporting by hmmclient.
Example of the issue: searching a profile HMM query against
a profile HMM target db results in a cryptic thrown exception
instead of a useful user-directed error message:

```
    src/hmmclient --db 2 tutorial/fn3.hmm
Fatal exception (source file p7_hmmd_search_stats.c, line 319):
Error: unknown enum type found in HMMD_SEARCH_STATS_Deserialize
Abort trap: 6
```

This was a problem in how the server was setting <status> in
client_msg_longjmp() and client_msg() calls; it was sometimes
erroneously passing the last value of <status> which had sometimes
been reset to eslOK after a failure that should be reported.