Addressing compilation errors in impl_vmx when configured with --enable-debugging.  These issues were first noted by Sean:
(1) In p7_MSVFilter_longtarget(), the code inside the "#if p7_DEBUGGING" block was SSE.  This escaped my eyes, as I hadn't tested on a VMX box with --enable-debugging configued.  Easy to resolve, by reusing an identically purposed block from p7_MSVFilter().

(2) Unused variables
msvfilter.c:267: warning: unused variable ‘xEv_prev’
msvfilter.c:466: warning: unused variable ‘e_unchanged’
msvfilter.c:465: warning: unused variable ‘hit_pthresh’

All 3 are in longtarget functions, and are just dangling variables used in SSE's more kludgy way of testing various conditions.  They can be (and were) removed safely

git-svn-id: https://svn.janelia.org/eddylab/eddys/src/hmmer/trunk@3498 db3e70e4-12e1-0310-b23f-81a6e3d09ba7